[features]
seeds = false
skip-lint = false
[programs.localnet]
ari_program = "74UigkEeKHT3PgQGUxXVfL2ghxK3tHYYc3LvZvi5rZH5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/khacvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000